# Generated by Django 2.2.4 on 2020-02-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
